version: '3.5'

services:

  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  
    user: root
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_home
      - /root/.ssh:/root/.ssh 
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config

networks:
  jenkins:
    driver: bridge

